# fly.toml app configuration file generated for hangman-telegram-bot on 2025-10-05T13:49:59+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hangman-telegram-bot'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[vm]]
  size = 'shared-cpu-1x'
